export const FETCH_IMAGES_REQUESTED =
  'FETCH_IMAGES_REQUESTED';
export const FETCH_IMAGE_REQUESTED =
  'FETCH_IMAGE_REQUESTED';
export const FETCH_IMAGES_SUCCESS = 'FETCH_IMAGES_SUCCESS';
export const FETCH_IMAGE_SUCCESS = 'FETCH_IMAGE_SUCCESS';
export const FETCH_ERROR = 'FETCH_ERROR';
